[package]
name = "transport-analysis"
version = "0.1.0"
authors = ["Emilio Lopez <ei_lopez@live.com>"]
edition = "2018"

[dependencies]
# bit-vec = "0.6.1"
bitvec = "0.19.3"
byteorder = "1.3.4"
clap = "2.33.3"