[package]
name = "transport-analysis"
version = "0.1.0"
authors = ["Emilio Lopez <eil11@case.edu>"]
edition = "2018"

[dependencies]
bit-array = "0.4.4"
typenum = "1.10.0"
byteorder = "1.3.1"
clap = "2.33.0"